# The Python Programming Language
__Functions__

In [1]:
x = 1
y = 2
x+y

3

In [2]:
x

1

In [6]:
def add_number(x,y,z):
    return x + y

print(add_number(1,2,3))

3


In [10]:
#since python is a dynamically languange the types
#declarations aren't requerid, so functions without return statement
#actually return 'None', which is a reserved word in python.

def returningNone(x,y,z):
    x+y+z

print(returningNone(1,2,3))

None


In [14]:
def add_numbers(x, y, z=None):
    if z == None:
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2))    
print(add_numbers(1, 2, 3))

3
6


In [18]:
def add_numbers(x, y, z=None, flag = False):
    if flag:
        print('Flag is True!')
    if z == None:
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2))    
print(add_numbers(1, 2, flag = True))

3
Flag is True!
None


__Types and sequences__

In [21]:
type('This is a string')

str

In [22]:
type(None)

NoneType

In [23]:
type(1)

int

In [24]:
type(1.0)

float

In [25]:
type(add_numbers)

function

In [26]:
#tuples are immutable
#we can use mixed types
x = (1, 'a', 2, 'b')
type(x)

In [31]:
#lists are immutable
#we can use mixed types
x = [1, 'a', 2, 'b']
x.append(3)
x.append('c')
print(type(x))

<class 'list'>


In [32]:
#for-each loop
for item in x:
    print(item)

1
a
2
b
3
c


In [33]:
#operations on lists
#+ is concatenation
[1,2] + [3,4]

[1, 2, 3, 4]

In [34]:
#* repeats the term
[1]*3

[1, 1, 1]

In [35]:
# in operator on lists
1 in [1,2,3]

True

In [38]:
#slicing strings
x = 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:2])
print(x[-1])
print(x[-4:-2])
print(x[:3])
print(x[3:])

T
T
Th
g
ri
Thi
s is a string


In [48]:
#split
firstname = 'Bruno'
lastname = 'Souza'
print(firstname + ' ' + lastname)

Bruno Souza


In [41]:
#dictionary
dic = {'Bruno' : 26}
dic['Bruno']


26

In [44]:
dic['Bruno'] = 18
dic['Bruno']
d

18

In [ ]:
#interating dictionaties by keys
for name in dic:
    print(name)
#interating dictionaties by values
for val in dic.values():
    print(val)
#interating dictionaties by key and values
for k, v in dic.items():
    print(k,v)

__Dates and Times__

In [2]:
import datetime as dt
import time as tm

In [3]:
tm.time()

1656013645.0535712

In [4]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2022, 6, 23, 19, 47, 25, 527659)

In [5]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2022, 6, 23, 19, 47, 25)

In [6]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [7]:
today = dt.date.today()

In [8]:
today - delta

datetime.date(2022, 3, 15)

In [9]:
today > today-delta

True

__Advanced Python Lambda and List Comprehensions__

In [12]:
#lambda is a python way of creating anonymous functions
#they are simple and short lived
#used when it's simplier create a function in one line
#instead of create a named function

myLambdaFunction = lambda a, b, c : a + b

myLambdaFunction(1,2,3)

#it cannot have a default value for lambda parameters
#you cannot have complex logic inside the lambda itself, 
#because it is limited to a single expression

3

In [ ]:
#list comprehensions are an inline way of creating lists

my_list = []
for num in range(0,1000):
    if num % 2 == 0:
        my_list.append(num)
my_list_comprehesion = [num for num in range(0,1000) if num % 2 == 0]

print(my_list==my_list_comprehesion)
#my_list and my_list_comprehesion are the same    

def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

print(times_tables() == [j*i for i in range(10) for j in range(10)])

In [2]:
#example
#Many organizations have user ids which are 
#constrained in some way. Imagine you work 
#at an internet service provider and the user ids are 
#all two letters followed by two numbers (e.g. aa49). 
#Your task at such an organization might be to hold a 
#record on the billing activity for each possible user. 

lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [c1+c2+d1+d2 for c1 in lowercase for c2 in lowercase for d1 in digits for d2 in digits]
#correct_answer == answer

__Advanced Python Objects__

In [5]:
#creating classes
class Person:
    department = 'School of Engineering'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location
    

In [8]:
#Objects in python do not have private or protected members
# You´ll always have full access to the atributes and methods 
#of an instanciated object
person = Person()
person.set_name('Bruno Souza')
person.set_location('Parnamirim')
print('{} live in {} and works in the department {}'.format(person.name,person.location, person.department))

Bruno Souza live in Parnamirim and works in the department School of Engineering


__Map functions__

In [10]:
#functional programming is a programming paradigm 
#in which you explicilty declare all parameters which could change
#through execution of a given function
#this functional programming is referred to as being sid-effect free
#because is a software contract that describes what can actually change
#by calling a function
#Functional programming causes one to think more heavily 
#while chaining operations together

#the map built-in funtion is one example of a functinal feature
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00,11.10,12.34,2.01]
#function below iterates through each list, compares items
#and choose the minimum (the cheapest)
cheapest = map(min,store1,store2)
print(cheapest)#this is a lazy evaluation
print(list(cheapest))
#the map functon returns a map object
#

[9.0, 11.0, 12.34, 2.01]


__Numpy__

In [2]:
import numpy as np
import math

In [3]:
#Array creation
#To create an Array we pass in a list as an argument in numpy array

a = np.array([1,2,3])
print(a)
print(a.ndim)#checking the number of dimension dimension
print(a.dtype) #checking the type of items in the array

b=np.array([[1,2,3],[4,5,6]])#two-dimensional array
print(b.shape) #the length of each dimension

# all data type in an array is the same

#Creating zero arrays specifying their shape
d = np.zeros((2,3))
print(d)
#Creating arrays of ones specifying their shape
e = np.ones((2,3))
print(e)
#Creating arrays of random numbers specifying their shape
f = np.random.rand(2,3)
print(f)
#creating a array with a sequence of numbers
#an array of number in the range of 10 and 50 (50 not included)
#2 refers to the step
g = np.arange(10,50,2)
print(g)
#similarly we can generate aray of sequence of float numbers
h = np.linspace(0,2,15)
print(h)#observe that 2 is included 

[1 2 3]
1
int64
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.54799964 0.09663506 0.56848819]
 [0.39118738 0.32312946 0.75363671]]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]


In [12]:
#Array operations
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a-b
print(c)
d = a*b
print(d)

e = (a-1)*3
print(e)

print(a < 21)

print(b%2==0)

#Matrix multiplication
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A*B)#elementwise product
print(A@B)#matrix product

#Indexing
a = np.array([10,20,30,40])
print(a[2])
A = np.array([[1,2],[3,4],[5,6]])
print(A[1,1])
print(A[[0,1,2],[0,1,1]])

##Boolean indexing
# it allow us to select arbitrary elements based on conditions.
#Find elements in A that are greater than 5
print(A[A>3])

#Slicing
print(a[:3])
print(a[2:4])
print(A[1:3,:])
#Slice an array is called passing by reference. 
#So modifying the sub array will modify original array

#there is difference between these two below
print(A[:,0])
print(A[:,0:1])

#others slicing
print(A[[0,2],:])

[ 9 18 27 36]
[ 10  40  90 160]
[ 27  57  87 117]
[ True  True False False]
[False  True False  True]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
30
4
[1 4 6]
[4 5 6]
[10 20 30]
[30 40]
[[3 4]
 [5 6]]
[1 3 5]
[[1]
 [3]
 [5]]
[[1 2]
 [5 6]]


__Manipulating text with Regular expressions__

In [7]:
import re

In [8]:
text = "I am in a bad mood"
if re.search("bad",text):
    print("He is in a bad mood!")

He is in a bad mood!


In [9]:
#Set operator: "[]".

grades = "ACAAAABCBAA"

print(re.findall("B",grades))
print(re.findall("[AB]",grades))
print(re.findall("[A][B-C]",grades))
print(re.findall("AB|AC",grades))
#^ inside set operatos means negation
print(re.findall("[^A]",grades))
#so ^ has one mean out of a set operator and other inside
print(re.findall("^[^A]",grades))

['B', 'B']
['A', 'A', 'A', 'A', 'A', 'B', 'B', 'A', 'A']
['AC', 'AB']
['AC', 'AB']
['C', 'B', 'C', 'B']
[]


In [10]:
#Quatifiers are the number of times you want a pattern 
#to be matched in order to match 
#sintax: regex{m,n} 
#where regex is the expression of character we're matching
#m is the minimum number of items you want it to be matched
#n is the maximum number of items you want

print(re.findall("A{2,10}",grades))
print(re.findall("A{1,1}A{1,1}",grades))
print(re.findall("AA",grades))
print(re.findall("A{2}",grades)) #2 in minimum and maximum
print(re.findall("A{1,10}B{1,10}C{1,10}",grades))

#* to match 0 or more times
#? to match 1 or more times
#+ to match 1 or more times

['AAAA', 'AA']
['AA', 'AA', 'AA']
['AA', 'AA', 'AA']
['AA', 'AA', 'AA']
['AAAABC']


In [11]:
with open("ferpa.txt") as file: 
    wiki = file.read()

print(re.findall('[\w ]*\[edit\]',wiki)) 
print(re.findall('[\w].*\[edit\]',wiki))
#this last one prints the same of the previous but it's not the same
#the first mathches for any word character including white spaces([\w ])
#that appears one or more time (*) immediatly followed by '[edit]'

#\w inside the set operator ([\w])
#is used to match any letter, including digits or numbers
#\w is a metacharacter and indicates a special pattern 
#of any letter or digit


print(re.findall('\[[0-9]\]',wiki))
print(re.findall('[A-Z][A-Z]+',wiki))
print(re.findall('[A-Z][a-z]+ [A-Z][a-z]+',wiki))

['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']
['Overview[edit]', 'Access to public records[edit]', 'Student medical records[edit]']
['[2]', '[2]', '[3]', '[4]', '[5]', '[6]', '[7]', '[8]', '[9]']
['FERPA', 'ID', 'FERPA', 'FERPA', 'FERPA', 'FERPA', 'FERPA', 'FERPA', 'FERPA', 'FERPA', 'HIPAA', 'FERPA', 'HIPAA']
['Education Data', 'Exchange Network', 'Internal Revenue', 'Buckley Amendment', 'Senator James', 'New York', 'Owasso Independent', 'School District', 'Supreme Court', 'Health Insurance', 'Accountability Act']


In [12]:
#Groups
#to group patterns together you use parentheses
print(re.findall('([\w].*)(\[edit\])',wiki))

for item in re.finditer('([\w].*)(\[edit\])',wiki):
    print(item.group(0))
    print(item.group(1))
    print(item.group(2))

#labeling or naming groups, for that use the syntax (?P<name_of_group>)
#where the parenthesis starts the group 
#the ?P indicates that this is an extension to basic regex
#and <name> is the dictionary key that we want to use wrapped in <>

for item in re.finditer('(?P<title>[\w].*)(?P<edit_link>\[edit\])',wiki):
    print(item.groupdict()['title'])

#other regex
#a . for any single character which is not a newline
# a \d for any digit
# and \s for any whitespace character, like spaces and tabs





[('Overview', '[edit]'), ('Access to public records', '[edit]'), ('Student medical records', '[edit]')]
Overview[edit]
Overview
[edit]
Access to public records[edit]
Access to public records
[edit]
Student medical records[edit]
Student medical records
[edit]
Overview
Access to public records
Student medical records


In [17]:
#Look-ahead and look-behind
with open("buddhist.txt") as file: 
    wiki = file.read()
pattern = """
(?P<title>.*) #the university title
(\ –\ located\ in\ ) #an indicator of the location
(?P<city>\w*) #the city the university is in
(,\ ) #separator for the state
(?P<state>\w*) #the state the city is in
"""
for item in re.finditer(pattern,wiki,re.VERBOSE):
    print(item.groupdict())

{'title': 'Dhammakaya Open University', 'city': 'Azusa', 'state': 'California'}
{'title': 'Dharmakirti College', 'city': 'Tucson', 'state': 'Arizona'}
{'title': 'Dharma Realm Buddhist University', 'city': 'Ukiah', 'state': 'California'}
{'title': 'Ewam Buddhist Institute', 'city': 'Arlee', 'state': 'Montana'}
{'title': 'Institute of Buddhist Studies', 'city': 'Berkeley', 'state': 'California'}
{'title': 'Maitripa College', 'city': 'Portland', 'state': 'Oregon'}
{'title': 'University of the West', 'city': 'Rosemead', 'state': 'California'}
{'title': 'Won Institute of Graduate Studies', 'city': 'Glenside', 'state': 'Pennsylvania'}


In [21]:
with open("nytimeshealth.txt", "r") as file: 
    health = file.read()
pattern = "#[\w\d]*(?=\s)"
print(re.findall(pattern,health))


['#askwell', '#pregnancy', '#Colorado', '#VegetarianThanksgiving', '#FallPrevention', '#Ebola', '#Ebola', '#ebola', '#Ebola', '#Ebola', '#EbolaHysteria', '#AskNYT', '#Ebola', '#Ebola', '#Liberia', '#Excalibur', '#ebola', '#Ebola', '#dallas', '#nobelprize2014', '#ebola', '#ebola', '#monrovia', '#ebola', '#nobelprize2014', '#ebola', '#nobelprize2014', '#Medicine', '#Ebola', '#Monrovia', '#Ebola', '#smell', '#Ebola', '#Ebola', '#Ebola', '#Monrovia', '#Ebola', '#ebola', '#monrovia', '#liberia', '#benzos', '#ClimateChange', '#Whole', '#Wheat', '#Focaccia', '#Tomatoes', '#Olives', '#Recipes', '#Health', '#Ebola', '#Monrovia', '#Liberia', '#Ebola', '#Ebola', '#Liberia', '#Ebola', '#blood', '#Ebola', '#organtrafficking', '#EbolaOutbreak', '#SierraLeone', '#Freetown', '#SierraLeone', '#ebolaoutbreak', '#kenema', '#ebola', '#Ebola', '#ebola', '#ebola', '#Ebola', '#ASMR', '#AIDS2014', '#AIDS', '#MH17', '#benzos']


In [45]:
a = 'www.aBC.com, abc.com, ab_c.de8f.com, abc, abc..com'
print(re.findall('[\w]+\.+',a))
ISBNs = '9971-5-0210-0, 960-425-059-0'
print(re.findall('\d{4}-\d{1}-\d{4}-\d{1}|\d{3}-\d{3}-\d{3}-\d{1}',ISBNs))
dois = 'doi:10.1038/nphys1170, doi:10.1002/0470841559.ch1'
print(re.findall('[0-9\.]+/[\w\.]+',dois))

['www.', 'aBC.', 'abc.', 'ab_c.', 'de8f.', 'abc..']
['9971-5-0210-0', '960-425-059-0']
['10.1038/nphys1170', '10.1002/0470841559.ch1']
