In [13]:
import numpy as np

a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

print(a5.shape == a1.shape)

def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

a = np.random.rand(4, 4)
b = np.random.rand(4, 4)
print(a)
print(l2_dist(a,b))
print(l2_dist(a.T,b.T))
print(np.reshape(a, (4 * 4)), np.reshape(b, (4 * 4)))
#print(np.reshape(a, (4 * 4)), np.reshape(b, (4 * 4, 1)))


True
[[0.70969714 0.6259323  0.62790487 0.81301469]
 [0.5690959  0.784987   0.3729628  0.32576395]
 [0.96661886 0.24923818 0.50535719 0.02459973]
 [0.94458264 0.35642009 0.10643422 0.79106658]]
1.0997371575402815
1.0997371575402815
[0.70969714 0.6259323  0.62790487 0.81301469 0.5690959  0.784987
 0.3729628  0.32576395 0.96661886 0.24923818 0.50535719 0.02459973
 0.94458264 0.35642009 0.10643422 0.79106658] [0.97469981 0.23385883 0.58830481 0.813104   0.64696915 0.3779089
 0.37540355 0.18098622 0.33796016 0.30578716 0.55170962 0.00768338
 0.90987303 0.16676245 0.68251567 0.93692054]


In [19]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [45]:
string = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'
result = re.findall('[https]:\/\/([A-Za-z0-9.]*)', string)
print(result)

['google.com', 'www.baidu.com']


In [41]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4


In [56]:
simple_string = """[Amy] is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""
    
print(re.findall('\[([A-Z][a-z]+\]',simple_string))


['[Amy]']


In [55]:
simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""
    
print(re.findall('[\w\-]+',simple_string))

['Amy', 'is', '5', 'years', 'old', 'and', 'her', 'sister', 'Mary', 'is', '2', 'years', 'old', 'Ruth', 'and', 'Peter', 'their', 'parents', 'have', '3', 'kids']
